### ISSUE TITLE
conda sim recipe having issue with cuda 11.7 on Fedora 35 NVidia Driver 515.57

### ISSUE THREAD

**Issue by BaNavyBlue** [tlambert03/CUDA_SIMrecon#17]
Hi I got the conda sim env to install on my system, but when I try to run the test code I get the
"!!Error occurred: cudaSetDevice failed"

I'm not sure if I'm just to new of a cuda version?  I'm also running 2 GPU in this machine.

I've also had an issue trying to compile the library locally using the "conda simbuild" environment.  One weird issue is it gives me access errors if I don't run build.sh as sudo or root, and I'm stopping at the 
`Could NOT find Boost (missing: Boost_INCLUDE_DIR program_options filesystem
  system)`
error

Will I need to roll back to an older cuda version?
Thanks Antone-

**Comment by BaNavyBlue** [comment]
I was able to get the "conda simbuild" recipe to work by re-downloading the repo, but it still has the "!!Error occurred: cudaSetDevice failed" problem.

**Comment by linshaova** [comment]
Hi Antone,

A silly question: have you made sure that CUDA runtime works on your Fedora? For example, have you run successfully "deviceQuery" from one of CUDA's sample code folders?

-lin

**Comment by BaNavyBlue** [comment]
Yes sorry, I was having strange revision issues, where the cuda drivers direct from nvidia were ahead of the official maintained nvidia drivers.  I was able to fix the other library issues.
