### ISSUE TITLE
Example library call

### ISSUE THREAD

**Issue by jackyko1991** [tlambert03/CUDA_SIMrecon#25]
Thank you for the great work. I am try to build a UI for repeatable user access to the SIM algo.

For a quick run I see there is a library call option of the class function: https://github.com/scopetools/cudasirecon/blob/97af94df03911735cc3ace81caf29ca36e153de0/src/cudaSirecon/cudaSirecon.cpp#L880-L882

Would there be any example or documentation of calling the reconstruction class? Any help will be much appreciated.

**Comment by tlambert03** [comment]
see pycudasirecon: https://github.com/tlambert03/pycudasirecon

**Comment by tlambert03** [comment]
btw, that repo also has a [GUI](https://github.com/tlambert03/pycudasirecon/blob/main/src/pycudasirecon/_napari.py) that can be used in [napari](https://github.com/napari/napari)
