### ISSUE TITLE
Example psf.dv data?

### ISSUE THREAD

**Issue by GenevieveBuckley** [tlambert03/CUDA_SIMrecon#6]
Is there a `psf.dv` test file? I don't see one in the `test_data/` folder alongside `raw.dv` and `otf.otf`, but it is referred to specifically in the README file describing use of the `makeotf` utility:
```
makeotf /path/to/psf.dv otf.otf -angle -1.855500 -ls 0.2075 -na 1.4 -nimm 1.515 -fixorigin 3 20 -leavekz 7 11 3
```

Context: I've managed to run the `cudasirecon` test data example on Windows, but am having issues on our Linux cluster. But `makeotf` isn't supported on Windows, so I still need to confirm I have a working installation somewhere else before I can try generating OTF images from our PSF files.

**Comment by tlambert03** [comment]
@linshaova has done some work on this recently, and may even fixed the difficulties with compiling makeotf on windows, so lemme look into it (but we can also just give you a precompiled Windows makeotf if not).  As for a test PSF, I can also find one for you

**Comment by GenevieveBuckley** [comment]
I'd be happy with a slightly awkward/cumbersome way of getting the OTF, since we shouldn't have to update it all that frequently. Thanks for your help!

**Comment by GenevieveBuckley** [comment]
Talley has found and shared a copy of the `test_data/` PSF with me on Dropbox. I think I see why it wasn't included in this github repo - the PSF is ~80MB and the limit for file uploads on github is 25MB. Compressing the psf file helps a little, but doesn't get it down under the limit.
