### ISSUE TITLE
cudasirecon libboost error

### ISSUE THREAD

**Issue by GenevieveBuckley** [tlambert03/CUDA_SIMrecon#7]
I'm having trouble installing `cudasirecon` on Linux and running the `test_data/` example. (I *can* get this running on Windows, but the `makeotf` utility function isn't supported on Windows, and I need to generate an OTF before I can use this for our own data).

I've tried the recommended installation from the README with Anaocnda on both:
1. Our linux based supercomputing cluster, and
2. A local Ubuntu linux machine (just in case there was something funny going on with the libraries on the cluster). 

To reproduce:
```
conda create -n sim -y -c talley -c conda-forge cudasirecon
conda activate sim
git clone https://github.com/scopetools/cudasirecon.git
cd cudasirecon/test_data
cudasirecon raw.dv data-PROC.dv otf.otf -c config
```

Which gives me this error:
```
cudasirecon: error while loading shared libraries: libboost_program_options.so.1.71.0: cannot open shared object file: No such file or directory
```

Do you have any advice?

**Comment by tlambert03** [comment]
Hmm, that boost lib should be in the conda install, so perhaps my conda recipe has become broken somehow. Probably shouldn’t matter, but what versions were the OS?

**Comment by GenevieveBuckley** [comment]
Local linux machine:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

**Comment by GenevieveBuckley** [comment]
Manually installing `libboost` into the conda environment worked well to fix this particular problem:
```
conda activate sim
conda install libboost=1.71
```

It might be possible `libboost` isn't included at all with the conda install, and the only reason this worked for me on Windows was that I maybe already had `libboost` there.

**Comment by tlambert03** [comment]
> It might be possible libboost isn't included at all with the conda install

It isn't included directly, but I just double checked the latest bundles at [anaconda cloud](https://anaconda.org/talley/cudasirecon/files) and `boost-cpp` (which contains `libboost`) is listed as a dependency in `info/index.json` (And it's in the [recipe](https://github.com/scopetools/cudasirecon/blob/master/conda-recipe/meta.yaml) that I use to build).  But it's been 10 months since I built that, so it's possible something has changed in the meantime.  I'm I've been slow to get to it.  each time I come back to this there's some activation energy to remind myself how I did everything.  What are the main things holding you back at the moment?

**Comment by GenevieveBuckley** [comment]
The main things holding me back at the moment are:
1. Generating an OTF suitable for our data (right now from theoretical values, but we'll measure the PSF experimentally later on once the experimental setup is more or less fixed)
2. Working out what the config file for our experimental parameters should look like, so I can run `cudasirecon` on our test data. I love how flexible cudasirecon is, btw. 

So I wouldn't attempt to address updating the conda recipe with any urgency, since we now know there is a simple workaround with `conda install libboost=1.71`. I would certainly appreciate any advice you have about the other two points I listed above, though. Thanks for your help here!

**Comment by tlambert03** [comment]
k, do you have an OMX (or are you willing to convert to [mrc](https://github.com/tlambert03/mrc)), or do you also need the TIFF support for your case?

**Comment by tlambert03** [comment]
I'm sorry @GenevieveBuckley, I've spent the morning trying to get this to build locally again, but I'm running into issues (#8)... so I'll need some time to get the build pipeline back in working order before I can help with this.  Should be pretty easy to address your two points there one we have it working.
Quick answers  are that 1) we don't support theoretical PSFs... only measured ones.  but I can probably send you one to use (though it will give you terrible results) and 2) this is usually the tough part, but I might be able to help if I get some of your data.

**Comment by GenevieveBuckley** [comment]
* We don't have OMX, but I am willing to convert back and forth between tiff & mrc file formats. (Our data is tiff)
* This might be a dumb question, but do I really need to build `cudasirecon` from source on linux? The anaconda install worked ok on the demo data after I installed `libboost` with conda, so I was hoping that `makeotf` and all the rest of it would also now work ok? 
* I can arrange to share some of our data with you, while we try and get this set up. I'll send you a message on zulip with my email.

**Comment by tlambert03** [comment]
> * We don't have OMX, but I am willing to convert back and forth between tiff & mrc file formats. (Our data is tiff)

ok, well @linshaova recently just enabled tiff support (#3) so it should work for tiff too now... but I haven't tried it out yet :)

> * This might be a dumb question, but do I really need to build `cudasirecon` from source on linux? The anaconda install worked ok on the demo data after I installed `libboost` with conda, so I was hoping that `makeotf` and all the rest of it would also now work ok?

no, _you_ shouldn't have to build anything from source.  You should just be able to conda install and be off and running.  But _I_ need to be able to build from source to try to generally update the builds :joy: (and I was curious why what I thought had been a working recipe without `libboost` was now no longer working).  Anyway, you may well be good to go if it was just about libboost.  with makeotf on linux, but not windows... but once I can get it building again, then I'll push updated conda builds with the new tiff capabilities from #3, and the new makeotf build on windows (thanks to the fact that @linshaova ported everything to FFTW3 in #3)

> * I can arrange to share some of our data with you, while we try and get this set up. I'll send you a message on zulip with my email.

👍

**Comment by tlambert03** [comment]
closing, installing from conda forge is now the recommended install:
`conda install -c conda-forge cudasirecon`
