### ISSUE TITLE
Documentation for makeotf options?

### ISSUE THREAD

**Issue by GenevieveBuckley** [tlambert03/CUDA_SIMrecon#9]
Where should I look to figure out what configuration options are available for `makeotf`?

I'm trying to work out what I should use to generate a correct OTF from our lab's data. I first checked `makeotf --help`, but that doesn't tell me about what command line options are available. From the README I know that `angle`, `ls`, `na`, `nimm`, `fixorigin`, and `leavekz` are all available options. Some of these are self-explanatory, but others not quite so much to me. The [source code here](https://github.com/scopetools/cudasirecon/blob/99bc478fde5c5c9b5c6d125946f4af124a9efd80/otf/makeotf.c#L96-L124) is still a little opaque to me too. It would be great if someone was able to point me in the right direction.

**Comment by tlambert03** [comment]
looks like that binary uses single dashes for arguments (even for long forms): `makeotf -help` or `makeotf -h` will work.  [here](https://github.com/scopetools/cudasirecon/blob/99bc478fde5c5c9b5c6d125946f4af124a9efd80/otf/makeotf.c#L1246-L1259) in the source code.  and here's the output:

```sh
❯ makeotf -help
Usage:
radialft [[input file] [output file]] [Options]

Options:
	-beaddiam F -- the diameter of the bead in microns (default is 0.12)
	-angle F -- the k0 vector angle with which the PSF is taken (default is 0)
	-ls x -- the illumination pattern's line spacing (in microns, default is 0.2)
	-nocompen -- do not perform bead size compensation (default is to perform)
	-5bands -- to output 5 OTF bands (default is combining higher-order's real and imag bands into one output
	-fixorigin kr1 kr2 -- the starting and end pixel for interpolation along kr axis (default is 2 and 9)
	-na x -- the (effective) NA of the objective
	-nimm x -- the index of refraction of the immersion liquid
	-leavekz kz1_1 kz1_2 kz2 -- the pixels to be retained on kz axis
	-I2M I2m_otf_file_name -- data contains I2M PSF and supply the I2M otf file name
	-background bkgd_value -- use the supplied number as the background to subtract
	-help or -h -- print this message

```

typical usage: 
```
makeotf image.dv test1.otf -angle -1.855500 -ls 0.2075 -na 1.4 -nimm 1.515 -fixorigin 3 20 -leavekz 7 11 3
```
- `leavekz` is used for OTF cleanup (settings areas outside of the support of the OTF to zero, [here](https://github.com/scopetools/cudasirecon/blob/99bc478fde5c5c9b5c6d125946f4af124a9efd80/otf/makeotf.c#L916))
- `fixorigin` is used to correct the singularity at the origin of the OTF, by extrapolating from pixels just outside of the origin back to the origin ([here](https://github.com/scopetools/cudasirecon/blob/99bc478fde5c5c9b5c6d125946f4af124a9efd80/otf/makeotf.c#L1123))

**Comment by GenevieveBuckley** [comment]
Thanks a ton, I totally misread and expected a double hyphen instead of a single one!
